export * from './Hero'
export * from './MyServices'
export * from './AboutMe'
export * from './Coments'
export * from './Faq'
export * from './Differential'
export * from './CallActon'
export * from './Contacts'